on:
  push:
    branches: ["main"]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build the app
        run: |
          yarn build
          mkdir upload
          cp -r package.json yarn.lock upload/
          cp -r dist/ upload/dist/

      - uses: actions/upload-artifact@v3
        with:
          name: backend
          if-no-files-found: error
          path: upload/

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        working-directory: ./frontend
        run: yarn

      - name: Build the app
        working-directory: ./frontend
        run: yarn build

      - uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/build/

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      MACHINE: rpi-audio
    needs:
      - build-backend
      - build-frontend
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: backend
          path: ${{github.workspace}}

      - uses: actions/download-artifact@v3
        with:
          name: frontend
          path: ${{github.workspace}}/frontend/build/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Setup Tailscale
        id: tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Add SSH key
        id: ssh
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p $HOME/.ssh
          MACHINE_IP="$(tailscale ip -4 $MACHINE)"
          ssh-keyscan $MACHINE_IP >> $HOME/.ssh/known_hosts
          echo "$SSH_KEY" > $HOME/.ssh/key
          chmod 600 $HOME/.ssh/key

      - name: Deploy
        run: |
          MACHINE_IP="$(tailscale ip -4 $MACHINE)"
          rsync -avr -e "ssh -i $HOME/.ssh/key" ./ "pi@[$MACHINE_IP]":/home/pi/auto-streaming-stt/
          ssh -i "$HOME/.ssh/key" "pi@$MACHINE_IP" 'cd /home/pi/auto-streaming-stt && yarn && pm2 restart index'
